apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: datasaude-app
  name: datasaude-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datasaude-app
  template:
    metadata:
      labels:
        app: datasaude-app
    spec:
      containers:
        - image: cbeloni/datasaude-app-amd64:latest
          name: datasaude-app
          envFrom:
          - secretRef:
              name: datasaude-app-env-staging
          ports:
            - containerPort: 3000