export const pacienteColumns = [
  { field: "id", headerName: "Id", width: 80 },
  { field: "CD_ATENDIMENTO", headerName: "Atendimento", width: 130 },
  { field: "NM_PACIENTE", headerName: "Paciente", width: 220, flex: 1 },
  { field: "DT_NASC", headerName: "Nascimento", width: 130 },
  { field: "DT_ATENDIMENTO", headerName: "Data atend.", width: 130 },
  { field: "TP_ATENDIMENTO", headerName: "Tipo", width: 110 },
  { field: "DS_ORI_ATE", headerName: "Origem", width: 160 },
  { field: "DS_LEITO", headerName: "Leito", width: 130 },
  { field: "DT_PREVISTA_ALTA", headerName: "Prev. alta", width: 130 },
  { field: "DT_ALTA", headerName: "Alta", width: 130 },
  { field: "CD_SGRU_CID", headerName: "SGRU CID", width: 110 },
  { field: "CD_CID", headerName: "CID", width: 90 },
  { field: "DS_CID", headerName: "Descrição CID", width: 240 },
  { field: "SN_INTERNADO", headerName: "Internado", width: 110 },
  { field: "TP_SEXO", headerName: "Sexo", width: 80 },
  { field: "latitude", headerName: "Latitude", width: 130 },
  { field: "longitude", headerName: "Longitude", width: 130 },
  { field: "poluente", headerName: "Poluente", width: 110 },
  { field: "indice_interpolado", headerName: "Índice", width: 110 },
];
