name: Deploy to Docker Hub

on:
  push:
    branches:
      - arm64 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: cbeloni
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        id: build
        uses: cloudposse/github-action-docker-build-push@main
        with:
          registry: registry.hub.docker.com
          organization: "cbeloni"
          repository: "datasaude-app"
          login: "cbeloni"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
          platforms: linux/arm64
