name: hard-deploy

on:
  push:
    branches: [ main ]
  # workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      SERVER_IP: 177.93.131.202

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: yarn install
    - name: Build page
      run: yarn run build   
    - run: mkdir ~/.ssh
    - run: 'echo "$SSH_KEY" >> ~/.ssh/github-action'
    - run: chmod 400 ~/.ssh/github-action
    - run: echo -e "Host $SERVER_IP\n\tUser ubuntu\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config
    - run: rsync -avP docker-compose.yml  Dockerfile nginx.conf  ubuntu@177.93.131.202:~
    - run: rsync -avP build/ ubuntu@177.93.131.202:~/html
    - run: ssh "$SERVER_IP" "docker-compose stop"
    - run: ssh "$SERVER_IP" "docker-compose down"
    - run: ssh "$SERVER_IP" "docker system prune -a --force"
    - run: ssh "$SERVER_IP" "docker-compose up -d"                            
